DELIMITER $$
CREATE PROCEDURE DropAllRows()
BEGIN
DELETE FROM AIprobeIO;
DELETE FROM AItrainIO;
DELETE FROM AudioLog;
DELETE FROM ConsentLog;
DELETE FROM Exclusions;
DELETE FROM Feedback;
DELETE FROM InstructNaughtiness;
DELETE FROM RCamyliIO;
DELETE FROM RCgeorgIO;
DELETE FROM Register;
DELETE FROM Relandings;
DELETE FROM TIprobeIO;
DELETE FROM TItrainIO;
DELETE FROM Unfocuses;

END$$
DELIMITER ;